### PR TITLE
setup: Fix build in mingw

### PR DESCRIPTION
**Pull request by Biswa96**
MINGW_CHOST is specific to msys2 build and packaging environment.
Instead, check sys.version which is available in any python env.
Also remove SecPkgContext_Bindings definition which has been added
in mingw-w64 headers.

### CODE REVIEW

**Comment by Biswa96** [comment]
MINGW_CHOST was previous added in this pull request https://github.com/mongodb/winkerberos/pull/22 by @totaam

**Comment by blink1073** [comment]
Hi @Biswa96, thanks for the patch!  I agree we'd want to be sure things still work on mingw32, mingw64, and msys.  If you'd like to work on the workflow, I think between  https://github.com/marketplace/actions/setup-msys2 and  https://github.com/marketplace/actions/install-mingw we could test building and importing the package.  We can't run the full test suite without the `kerberos` server unfortunately.

**Comment by Biswa96** [comment]
OK, I have added the build workflow.

**Comment by Biswa96** [comment]
Done. You can see my fork for the CI runs.

**Comment by blink1073** [comment]
Hmm, it looks like I don't have access to see the runs:

image

**Comment by blink1073** [comment]
Ah, it just wasn't in the UI, I found https://github.com/Biswa96/winkerberos/actions/runs/1808120979

**Review by blink1073 — APPROVED** [review]
Great, thank you!

**Pull request merged**
