### PR TITLE
Add NTLM SSP

### PR DESCRIPTION
**Pull request by alxchk**
Add NTLM support with no cost

### CODE REVIEW

**Comment by behackett** [comment]
That's interesting. How would someone use WinKerberos to authenticate with NTLM? Can you add an example to https://github.com/mongodb-labs/winkerberos/blob/master/doc/index.rst?

**Comment by alxchk** [comment]
Just use NTLM mechid, that is. Actually this patch is needed only because you check  PyCapsule :)

**Comment by behackett** [comment]
A self contained example in the docs would be _really_ helpful to users (and me, since users will ask me and I have no experience with NTLM). I looked at the project you're using WinKerberos in. It doesn't look like the kerberos example in our docs will work for NTLM.

**Comment by behackett** [comment]
High, I'm going to close this without merging. If you can provide some documentation or at least a use case I'm happy to reconsider it. I have no idea how you would use WinKerberos to do NTLM auth, so have no way to provide any kind of help to users about it.

**Pull request closed without merging**
